// data models related to tests

export enum TestSource {
  BASIC = 'basic',
  ADVANCED = 'advanced',
  UPLOAD = 'upload',
  API = 'api',
  CLI = 'cli',
  AGENT = 'agent',
  UNKNOWN = 'unknown',
}

// just for type checking
type ConfigJson = {
  url: string;
  date: string;
  options: {
    browser: string;
  };
};

export class TestConfig {
  test_id: string;
  zip_key: string;
  name?: string;
  description?: string;
  source: TestSource;
  url: string;
  test_date: number;
  browser: string;
  created_at: number = Math.floor(Date.now() / 1000);
  updated_at: number = Math.floor(Date.now() / 1000);

  /// <summary>
  /// Create a TestConfig from a config file that is
  /// generated by Telescope agent.
  /// </summary>
  /// <param name="config">The config object</param>
  /// <param name="zipKey">R2 storage key (content hash)</param>
  /// <returns>The TestConfig object</returns>
  constructor(
    config: ConfigJson,
    zipKey: string,
    source: TestSource,
    name?: string,
    description?: string,
  ) {
    this.test_id = this.generateTestId();
    this.zip_key = zipKey;
    this.name = name;
    this.description = description;
    this.source = source;
    this.url = config.url;
    this.test_date = Math.floor(new Date(config.date).getTime() / 1000);
    this.browser = config.options.browser;
  }

  private generateTestId(): string {
    const date_ob = new Date();
    const date = date_ob.getDate().toString().padStart(2, '0');
    const month = (date_ob.getMonth() + 1).toString().padStart(2, '0');
    const year = date_ob.getFullYear();
    const hour = date_ob.getHours().toString().padStart(2, '0');
    const minute = date_ob.getMinutes().toString().padStart(2, '0');
    const second = date_ob.getSeconds().toString().padStart(2, '0');
    return `${year}_${month}_${date}_${hour}_${minute}_${second}_${crypto.randomUUID()}`;
  }
}
