name: Test PRs
permissions:
  contents: read

on:
  push:
    branches: [main]
    paths-ignore:
      - "packages/telescope-web/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "packages/telescope-web/**"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      HOME: /root
    container:
      # make sure to match this version with the one in package.json
      image: mcr.microsoft.com/playwright:v1.59.1-noble

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./packages/telescope/package-lock.json"

      - name: Install xz-utils
        run: apt-get update && apt-get install -y xz-utils

      - name: Set up FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3

      - name: Install dependencies
        # don't install the browsers since we're using the pre-built container
        working-directory: ./packages/telescope
        run: npm ci --ignore-scripts

      - name: Build TypeScript
        working-directory: ./packages/telescope
        run: npm run build

      - name: Run tests
        working-directory: ./packages/telescope
        run: npm test

      - name: List all results
        if: ${{ always() }}
        working-directory: ./packages/telescope
        run: find results
